//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActionT
    {
        public int ActionTId { get; set; }
        public int ActionUnitId { get; set; }
        public int ActionUserGroupId { get; set; }
        public Nullable<int> ActionAuthorityTypeId { get; set; }
        public int ActionUserId { get; set; }
        public int ActionConfId { get; set; }
        public string ActionUserInitial { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string ActionComment { get; set; }
        public Nullable<int> ActionUserDelId { get; set; }
        public Nullable<int> ActionUserTempId { get; set; }
        public int RenderInLine { get; set; }
        public int RenderAutoOpen { get; set; }
        public int IsKeyUnit { get; set; }
        public int RecordStatus { get; set; }
        public Nullable<int> FlowSequence { get; set; }
        public Nullable<int> NextActionId { get; set; }
        public string SerialFrom { get; set; }
        public Nullable<int> PrevActionId { get; set; }
        public string SerialTo { get; set; }
        public Nullable<int> ResultCall { get; set; }
        public string RClassA { get; set; }
        public string RClassB { get; set; }
        public string RClassC { get; set; }
        public int IsPosted { get; set; }
        public int VoteUp { get; set; }
        public string VoteUpList { get; set; }
        public int VoteDown { get; set; }
        public string VoteDownList { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime Dated { get; set; }
        public string ActionLog { get; set; }
        public Nullable<int> MasterId { get; set; }
        public int ProcessId { get; set; }
        public int StageId { get; set; }
        public int SectionId { get; set; }
        public int BUnitId { get; set; }
        public int DevisionId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> IsRouted { get; set; }
        public Nullable<int> IsDelegated { get; set; }
        public Nullable<int> IsRecycled { get; set; }
        public Nullable<int> IsRemind { get; set; }
        public Nullable<int> IsCancel { get; set; }
        public Nullable<int> IsUndo { get; set; }
        public Nullable<int> IsHold { get; set; }
        public Nullable<int> IsExtra1 { get; set; }
        public Nullable<int> IsExtra2 { get; set; }
        public Nullable<bool> IsSkipped { get; set; }
        public Nullable<bool> ShowNotApplicable { get; set; }
        public Nullable<bool> ShowAgree { get; set; }
        public Nullable<bool> ShowDisagree { get; set; }
        public Nullable<bool> IsTimerStart { get; set; }
        public Nullable<System.DateTime> TimerStartDatetime { get; set; }
        public Nullable<bool> IsTimerStop { get; set; }
        public Nullable<System.DateTime> TimerStopDatetime { get; set; }
        public Nullable<bool> IsJumper { get; set; }
        public Nullable<int> JumptoUnitId { get; set; }
        public Nullable<bool> IsMandatoryToggleable { get; set; }
        public Nullable<bool> IsExtraBit { get; set; }
        public Nullable<int> IsClose { get; set; }
        public bool IsOriginalTemplate { get; set; }
    }
}
