//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RecordId { get; set; }
        public Nullable<int> Activity_Lok { get; set; }
        public Nullable<int> Operation_Lok { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> WorkSpaceId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> ActionUnitId { get; set; }
        public Nullable<int> CommandId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> IsMajorActivity { get; set; }
        public Nullable<int> ExtraId { get; set; }
        public string ExtraField { get; set; }
        public Nullable<int> CommandStatus { get; set; }
        public string Msg { get; set; }
        public string ClientIP { get; set; }
        public System.DateTime Dated { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual AppLockup AppLockup { get; set; }
    }
}
