//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppLockup
    {
        public AppLockup()
        {
            this.ActivityLogs = new HashSet<ActivityLog>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string Desc { get; set; }
        public string Icon { get; set; }
        public string IconClass { get; set; }
        public string GeneralClass { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<ActivityLog> ActivityLogs { get; set; }
    }
}
