//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BUnitsT
    {
        public int BUnitId { get; set; }
        public int BUnitType { get; set; }
        public string BUnitAbbr { get; set; }
        public string BUnitGUID { get; set; }
        public string BUnitName { get; set; }
        public string BUnitNumber { get; set; }
        public string BUnitSerial { get; set; }
        public int BUnitParentId { get; set; }
        public string BUnitWebsite { get; set; }
        public string BUnitAbout { get; set; }
        public string BUnitHeader { get; set; }
        public string BUnitLogo { get; set; }
        public string BUnitAddress1 { get; set; }
        public string BUnitAddress2 { get; set; }
        public string BUnitState { get; set; }
        public string BUnitCountryId { get; set; }
        public string BUnitZip { get; set; }
        public string BUnitTelephone { get; set; }
        public string BUnitFax { get; set; }
        public string BUnitPOBOX { get; set; }
        public Nullable<int> BUnitAdminGroup { get; set; }
        public int BUnitAccount { get; set; }
        public Nullable<int> BUnitFolderId { get; set; }
        public string BUnitFolderName { get; set; }
        public string BUnitFolderPath { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Dated { get; set; }
        public Nullable<int> WorkSpaceFolderId { get; set; }
        public Nullable<int> ProjectFolderId { get; set; }
        public Nullable<int> SystemFolderId { get; set; }
        public Nullable<int> ProcessFolderId { get; set; }
        public Nullable<int> FeedsFolderId { get; set; }
        public Nullable<int> LibraryFolderId { get; set; }
        public Nullable<int> GeneralFolderId { get; set; }
        public Nullable<int> BaseUserGroupId { get; set; }
        public Nullable<int> AdminUsersGroupId { get; set; }
        public Nullable<int> MemberUsersGroupId { get; set; }
        public Nullable<int> AuditorUsersGroupId { get; set; }
        public bool AllowIntro { get; set; }
        public bool AllowIntroOpen { get; set; }
        public bool AllowProjects { get; set; }
        public bool AllowProjectsOpen { get; set; }
        public bool AllowProcess { get; set; }
        public bool AllowProcessOpen { get; set; }
        public bool AllowFiles { get; set; }
        public bool AllowFilesOpen { get; set; }
        public bool AllowUsers { get; set; }
        public bool AllowUsersOpen { get; set; }
        public bool AllowLog { get; set; }
        public bool AllowLogOpen { get; set; }
        public bool AllowCharts { get; set; }
        public bool AllowChartsOpen { get; set; }
        public bool AllowExtra { get; set; }
        public bool AllowExtraOpen { get; set; }
        public bool AllowWorkSpaces { get; set; }
        public bool AllowWorkSpacesOpen { get; set; }
        public bool AllowDelegation { get; set; }
        public bool AllowDelegationOpen { get; set; }
        public bool AllowChilds { get; set; }
        public bool AllowChildsOpen { get; set; }
        public bool AllowGalary { get; set; }
        public bool AllowGalaryOpen { get; set; }
        public bool AllowFeeds { get; set; }
        public bool AllowFeedsOpen { get; set; }
        public bool AllowStatistics { get; set; }
        public bool AllowStatisticOpen { get; set; }
        public bool AllowEx1 { get; set; }
        public bool AllowEx1Open { get; set; }
        public bool AllowEx2 { get; set; }
        public bool AllowEx2Open { get; set; }
        public bool AllowSummary { get; set; }
        public bool AllowSummaryOpen { get; set; }
        public Nullable<int> ExtraField1 { get; set; }
        public Nullable<int> ExtraField2 { get; set; }
    }
}
