//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat
    {
        public int ChatId { get; set; }
        public string Message { get; set; }
        public System.DateTime DateSent { get; set; }
        public int UserId { get; set; }
        public int ProccessId { get; set; }
        public Nullable<int> ActionUnitId { get; set; }
        public Nullable<int> ActionTId { get; set; }
        public int BUnitId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> WorspaceId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> VoteId { get; set; }
        public Nullable<int> LogSectionId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Dated { get; set; }
    }
}
