//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicatorDetailsT
    {
        public int Id { get; set; }
        public int CommTMainId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> UserConformance { get; set; }
        public string UserInitial { get; set; }
        public string UserComment { get; set; }
        public Nullable<System.DateTime> DateActioned { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<int> DelegateId { get; set; }
        public Nullable<int> LeaderId { get; set; }
        public string LeaderComment { get; set; }
        public Nullable<System.DateTime> LeaderActionDate { get; set; }
        public Nullable<bool> LeaderActioned { get; set; }
        public Nullable<int> ExtraId { get; set; }
        public string ExtraText { get; set; }
        public Nullable<int> QuestionairMasterId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> LeaderNotificationId { get; set; }
        public Nullable<int> UserLevelId { get; set; }
        public Nullable<int> ExtraRefId { get; set; }
        public string ExtraRefText { get; set; }
        public string ExtraComment { get; set; }
        public Nullable<int> ExtraRefNumber { get; set; }
    }
}
