//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunicatorT
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string TaskGUID { get; set; }
        public string Serial { get; set; }
        public Nullable<int> TypeId { get; set; }
        public string Icon { get; set; }
        public string IconClass { get; set; }
        public string Description { get; set; }
        public string DescClass { get; set; }
        public string Tag { get; set; }
        public string TagClass { get; set; }
        public Nullable<System.DateTime> DateSince { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public string DateClass { get; set; }
        public string RecController { get; set; }
        public string RecAction { get; set; }
        public Nullable<int> Param { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public Nullable<int> EmailRef { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> WorkSpaceId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public string ProcessNumber { get; set; }
        public Nullable<int> ActionId { get; set; }
        public string ActionNumber { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Dated { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectNumber { get; set; }
        public string UserTaggs { get; set; }
        public string Subject { get; set; }
        public Nullable<int> UserFlag { get; set; }
        public Nullable<System.DateTime> UserFlagDate { get; set; }
        public string UserResponse { get; set; }
        public Nullable<System.DateTime> UserCompletionDate { get; set; }
        public Nullable<int> OriginatorId { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
        public Nullable<bool> IsDissmissed { get; set; }
        public Nullable<System.DateTime> DissmissDate { get; set; }
        public string FileGUID { get; set; }
        public Nullable<int> FolderId { get; set; }
        public string FolderGUID { get; set; }
        public Nullable<int> DelegateId { get; set; }
        public Nullable<int> QuestionMasterId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> TaskCommunicationId { get; set; }
        public Nullable<int> VoteId { get; set; }
        public int SuccessQuota { get; set; }
        public int TotalAgreeVote { get; set; }
        public int TotalDisagreeVote { get; set; }
        public int TotalNAVote { get; set; }
        public int TotalVotes { get; set; }
    }
}
