//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTX
    {
        public CompanyTX()
        {
            this.UsersInGroups = new HashSet<UsersInGroup>();
        }
    
        public int CompanyId { get; set; }
        public string CompanyName { get; set; }
        public string CompanyWebsite { get; set; }
        public string CompanyCountryId { get; set; }
        public string CompanyLocation { get; set; }
        public string CompanyAbout { get; set; }
        public string CompanyLogo { get; set; }
        public string CompanyTelephone { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Dated { get; set; }
    
        public virtual ICollection<UsersInGroup> UsersInGroups { get; set; }
    }
}
