//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string CustomerNo { get; set; }
        public string CustomerAcctNo { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerContactNo { get; set; }
        public string CustomerWebsite { get; set; }
        public bool CustomerStatus { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public int CustomerClass { get; set; }
    }
}
