//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProcessadmindbEntities : DbContext
    {
        public ProcessadmindbEntities()
            : base("name=ProcessadmindbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ActionT> ActionTs { get; set; }
        public DbSet<ActionTA> ActionTAs { get; set; }
        public DbSet<ActivityLog> ActivityLogs { get; set; }
        public DbSet<AppLockup> AppLockups { get; set; }
        public DbSet<BroadcastT> BroadcastTs { get; set; }
        public DbSet<BUnitsT> BUnitsTs { get; set; }
        public DbSet<Chat> Chats { get; set; }
        public DbSet<CommandLockup> CommandLockups { get; set; }
        public DbSet<CommunicatorDetailsT> CommunicatorDetailsTs { get; set; }
        public DbSet<CommunicatorT> CommunicatorTs { get; set; }
        public DbSet<CompanyTX> CompanyTXes { get; set; }
        public DbSet<Consequence_Lockup> Consequence_Lockup { get; set; }
        public DbSet<CountryList> CountryLists { get; set; }
        public DbSet<DateExtensionT> DateExtensionTs { get; set; }
        public DbSet<DelegateT> DelegateTs { get; set; }
        public DbSet<DelegationDetailsT> DelegationDetailsTs { get; set; }
        public DbSet<DelegationT> DelegationTs { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<EmailsT> EmailsTs { get; set; }
        public DbSet<FilesUploaded> FilesUploadeds { get; set; }
        public DbSet<FilesUploadedFM> FilesUploadedFMS { get; set; }
        public DbSet<FlowsInWorkSpace> FlowsInWorkSpaces { get; set; }
        public DbSet<FMSFileType> FMSFileTypes { get; set; }
        public DbSet<FoldersLibrary> FoldersLibraries { get; set; }
        public DbSet<GoogleMarker> GoogleMarkers { get; set; }
        public DbSet<ImpactsT> ImpactsTs { get; set; }
        public DbSet<InspectionConfidence_Lockup> InspectionConfidence_Lockup { get; set; }
        public DbSet<LinksUploaded> LinksUploadeds { get; set; }
        public DbSet<Location> Locations { get; set; }
        public DbSet<MainRiskManagment> MainRiskManagments { get; set; }
        public DbSet<MapData> MapDatas { get; set; }
        public DbSet<MarksUploaded> MarksUploadeds { get; set; }
        public DbSet<MatrixDetail> MatrixDetails { get; set; }
        public DbSet<MatrixT> MatrixTs { get; set; }
        public DbSet<MenuItem> MenuItems { get; set; }
        public DbSet<NotificationLockup> NotificationLockups { get; set; }
        public DbSet<NotificationPriority_Lockup> NotificationPriority_Lockup { get; set; }
        public DbSet<NotificationsT> NotificationsTs { get; set; }
        public DbSet<OperationLockup> OperationLockups { get; set; }
        public DbSet<OptionsLockup> OptionsLockups { get; set; }
        public DbSet<PaymentRegistration> PaymentRegistrations { get; set; }
        public DbSet<ProcessCategory> ProcessCategories { get; set; }
        public DbSet<ProcessFieldLookup> ProcessFieldLookups { get; set; }
        public DbSet<ProcessFieldSetup> ProcessFieldSetups { get; set; }
        public DbSet<ProcessMaster> ProcessMasters { get; set; }
        public DbSet<ProcessStructureT> ProcessStructureTs { get; set; }
        public DbSet<ProcessStructureTA> ProcessStructureTAs { get; set; }
        public DbSet<ProjectsT> ProjectsTs { get; set; }
        public DbSet<ProjectTDetail> ProjectTDetails { get; set; }
        public DbSet<Questionnaire> Questionnaires { get; set; }
        public DbSet<QuestionnaireA> QuestionnaireAs { get; set; }
        public DbSet<QuestionnaireGroup> QuestionnaireGroups { get; set; }
        public DbSet<QuestionnaireMaster> QuestionnaireMasters { get; set; }
        public DbSet<QuestionnaireMasterA> QuestionnaireMasterAs { get; set; }
        public DbSet<QuestionnaireScoring> QuestionnaireScorings { get; set; }
        public DbSet<Risk_Lockup> Risk_Lockup { get; set; }
        public DbSet<SubRiskManagement> SubRiskManagements { get; set; }
        public DbSet<SystemProcessRootT> SystemProcessRootTs { get; set; }
        public DbSet<SystemProcessT> SystemProcessTs { get; set; }
        public DbSet<TaskFeedT> TaskFeedTs { get; set; }
        public DbSet<TourT> TourTs { get; set; }
        public DbSet<UserGroup> UserGroups { get; set; }
        public DbSet<UserPicture> UserPictures { get; set; }
        public DbSet<UserPrivilegeT> UserPrivilegeTs { get; set; }
        public DbSet<UserProfile> UserProfiles { get; set; }
        public DbSet<UsersInGroup> UsersInGroups { get; set; }
        public DbSet<UsersInHirarchy> UsersInHirarchies { get; set; }
        public DbSet<UsersInHirarchyT> UsersInHirarchyTs { get; set; }
        public DbSet<VoteMaster> VoteMasters { get; set; }
        public DbSet<VotesXT> VotesXTs { get; set; }
        public DbSet<VoteT> VoteTs { get; set; }
        public DbSet<VoteTDetail> VoteTDetails { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<WorkSpaceT> WorkSpaceTs { get; set; }
        public DbSet<DateExtensions__> DateExtensions__ { get; set; }
        public DbSet<MapLongLat> MapLongLats { get; set; }
        public DbSet<ProcessstructureTA_VW> ProcessstructureTA_VW { get; set; }
        public DbSet<vw_ActionT_Row> vw_ActionT_Row { get; set; }
        public DbSet<vw_ActionTA_Row> vw_ActionTA_Row { get; set; }
        public DbSet<vw_ActionTA_Row___> vw_ActionTA_Row___ { get; set; }
        public DbSet<vw_ActvityLog> vw_ActvityLog { get; set; }
        public DbSet<Vw_BroadcastComm> Vw_BroadcastComm { get; set; }
        public DbSet<Vw_Broadcasts> Vw_Broadcasts { get; set; }
        public DbSet<vw_BroadcastsList> vw_BroadcastsList { get; set; }
        public DbSet<Vw_Comm_Details> Vw_Comm_Details { get; set; }
        public DbSet<Vw_CommunicatorFeeds> Vw_CommunicatorFeeds { get; set; }
        public DbSet<vw_ConformanceLockup> vw_ConformanceLockup { get; set; }
        public DbSet<Vw_Delegation> Vw_Delegation { get; set; }
        public DbSet<Vw_Delegation_> Vw_Delegation_ { get; set; }
        public DbSet<Vw_DExtensions> Vw_DExtensions { get; set; }
        public DbSet<Vw_Feeds> Vw_Feeds { get; set; }
        public DbSet<vw_FileuploadList> vw_FileuploadList { get; set; }
        public DbSet<Vw_FlowCounterByUserandDate> Vw_FlowCounterByUserandDate { get; set; }
        public DbSet<Vw_FLowCountersByDate> Vw_FLowCountersByDate { get; set; }
        public DbSet<Vw_FlowsInWorkSpaces> Vw_FlowsInWorkSpaces { get; set; }
        public DbSet<Vw_FlowsInWorkSpaces_Search> Vw_FlowsInWorkSpaces_Search { get; set; }
        public DbSet<vw_FolderTree> vw_FolderTree { get; set; }
        public DbSet<vw_GetChatMessagesWithUserInfo> vw_GetChatMessagesWithUserInfo { get; set; }
        public DbSet<vw_LinksuploadList> vw_LinksuploadList { get; set; }
        public DbSet<vw_logTotal> vw_logTotal { get; set; }
        public DbSet<vw_MarksUploadList> vw_MarksUploadList { get; set; }
        public DbSet<vw_Master_Process> vw_Master_Process { get; set; }
        public DbSet<Vw_NotificaionFeeds> Vw_NotificaionFeeds { get; set; }
        public DbSet<Vw_Process_Exts> Vw_Process_Exts { get; set; }
        public DbSet<Vw_Process_tasks> Vw_Process_tasks { get; set; }
        public DbSet<Vw_Process_tasks_v1> Vw_Process_tasks_v1 { get; set; }
        public DbSet<Vw_Process_tasks_v2> Vw_Process_tasks_v2 { get; set; }
        public DbSet<Vw_Process_Votes> Vw_Process_Votes { get; set; }
        public DbSet<Vw_Process_Votes_xx> Vw_Process_Votes_xx { get; set; }
        public DbSet<vw_ProcessFlow> vw_ProcessFlow { get; set; }
        public DbSet<vw_ProcessFlowA> vw_ProcessFlowA { get; set; }
        public DbSet<Vw_ProcessMaster> Vw_ProcessMaster { get; set; }
        public DbSet<vw_ProcessStructureTSystem> vw_ProcessStructureTSystem { get; set; }
        public DbSet<Vw_ProcessUnits_Questionnaire> Vw_ProcessUnits_Questionnaire { get; set; }
        public DbSet<Vw_ProcessUnits_QuestionnaireA> Vw_ProcessUnits_QuestionnaireA { get; set; }
        public DbSet<Vw_ProcessUnits_QuestionnaireA__> Vw_ProcessUnits_QuestionnaireA__ { get; set; }
        public DbSet<Vw_Project_tasks> Vw_Project_tasks { get; set; }
        public DbSet<Vw_Project_Votes> Vw_Project_Votes { get; set; }
        public DbSet<Vw_ProjectsT> Vw_ProjectsT { get; set; }
        public DbSet<Vw_Questionaire> Vw_Questionaire { get; set; }
        public DbSet<Vw_QuestionaireMaster> Vw_QuestionaireMaster { get; set; }
        public DbSet<Vw_QuestionaireMasterA> Vw_QuestionaireMasterA { get; set; }
        public DbSet<Vw_QuestionaireMasterXX> Vw_QuestionaireMasterXX { get; set; }
        public DbSet<Vw_QuestionnaireA> Vw_QuestionnaireA { get; set; }
        public DbSet<vw_UserGroups> vw_UserGroups { get; set; }
        public DbSet<Vw_UserInHirarchy> Vw_UserInHirarchy { get; set; }
        public DbSet<Vw_UserInHirarchyT> Vw_UserInHirarchyT { get; set; }
        public DbSet<Vw_UserPrivilege> Vw_UserPrivilege { get; set; }
        public DbSet<vw_UserProfile_BUnits> vw_UserProfile_BUnits { get; set; }
        public DbSet<vw_UserRoles> vw_UserRoles { get; set; }
        public DbSet<vw_userslist> vw_userslist { get; set; }
        public DbSet<Vw_VMAP> Vw_VMAP { get; set; }
        public DbSet<Vw_VoteMaster> Vw_VoteMaster { get; set; }
        public DbSet<Vw_Votes> Vw_Votes { get; set; }
        public DbSet<Vw_VoteTDetails> Vw_VoteTDetails { get; set; }
        public DbSet<Vw_WorkSpaceT> Vw_WorkSpaceT { get; set; }
        public DbSet<vw_WorldMap> vw_WorldMap { get; set; }
        public DbSet<Vw_WorldMap2> Vw_WorldMap2 { get; set; }
        public DbSet<Customer> Customers { get; set; }
    }
}
