//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DateExtensions__
    {
        public int Id { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public Nullable<int> CreaterUserId { get; set; }
        public string CreaterComment { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> VoteId { get; set; }
        public Nullable<int> WorkSpaceId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> DivisonId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<int> ApproverUserId { get; set; }
        public string ApproverComment { get; set; }
    }
}
