//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelegationDetailsT
    {
        public int Id { get; set; }
        public int DelegationMID { get; set; }
        public Nullable<int> ProcessTypeId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public string ProcessNumber { get; set; }
        public string ProcessSerial { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsNotified { get; set; }
        public bool IsListed { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> DateAttended { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Style1 { get; set; }
        public string Style2 { get; set; }
    }
}
