//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DelegateT
    {
        public int DelegId { get; set; }
        public int DelegUserFId { get; set; }
        public int DelegUserTId { get; set; }
        public System.DateTime DelegDateFrom { get; set; }
        public System.DateTime DelegDateTo { get; set; }
        public Nullable<int> DelegStatus { get; set; }
        public string DelegNote { get; set; }
        public int DelegCreatorId { get; set; }
        public Nullable<int> DelegCompanyId { get; set; }
        public Nullable<int> DelegBUnitId { get; set; }
        public Nullable<int> DeleProcessId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime Dated { get; set; }
    }
}
