//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailsT
    {
        public int MailId { get; set; }
        public string MailGUID { get; set; }
        public string MailSubject { get; set; }
        public string MailBody { get; set; }
        public int FromUserId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public string ToUserIdsList { get; set; }
        public string ToUserList { get; set; }
        public Nullable<int> CCUserId { get; set; }
        public string CCUserIdsList { get; set; }
        public string CCUserList { get; set; }
        public Nullable<int> BCCUserId { get; set; }
        public string BCCUserIdsList { get; set; }
        public string BCCUserList { get; set; }
        public string FromAddress { get; set; }
        public string ToAddress { get; set; }
        public string CCAddress { get; set; }
        public string BCCAddress { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsRead { get; set; }
        public Nullable<System.DateTime> ReadDateTime { get; set; }
        public bool IsAttachement { get; set; }
        public bool IsStar { get; set; }
        public Nullable<int> MailBoxType { get; set; }
        public Nullable<int> ReplyForEmailId { get; set; }
        public bool IsSentPending { get; set; }
        public bool IsSent { get; set; }
        public Nullable<System.DateTime> SentDateTime { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public bool IsDraft { get; set; }
        public bool IsSpamJunk { get; set; }
        public string FileGUID { get; set; }
    }
}
