//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FilesUploaded
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string url { get; set; }
        public string thumbnailUrl { get; set; }
        public decimal size { get; set; }
        public string progress { get; set; }
        public string newName { get; set; }
        public string deletetype { get; set; }
        public string deleteurl { get; set; }
        public string description { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ProccessId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> DevisionId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string FileFolderId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsHidden { get; set; }
        public Nullable<bool> IsPrivate { get; set; }
        public Nullable<System.DateTime> FileDate { get; set; }
        public Nullable<int> TaskId { get; set; }
        public Nullable<int> ExtraId { get; set; }
        public Nullable<int> CommentId { get; set; }
        public Nullable<int> VoteId { get; set; }
        public Nullable<int> FolderId { get; set; }
        public Nullable<int> WorkSpaceId { get; set; }
        public Nullable<int> EmailId { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public string NewGUID { get; set; }
        public Nullable<bool> IsLatest { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string FGUID { get; set; }
        public Nullable<int> FileClassificationId { get; set; }
        public string FileClass { get; set; }
        public Nullable<int> FileStageId { get; set; }
        public Nullable<int> FileActionUnitId { get; set; }
        public string FileActionUnit { get; set; }
        public string FileStage { get; set; }
        public Nullable<int> FileExtra1 { get; set; }
        public string FileExtra2 { get; set; }
        public Nullable<bool> FileExtra3 { get; set; }
    }
}
