//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlowsInWorkSpace
    {
        public int Id { get; set; }
        public int CustomFlowId { get; set; }
        public int OriginalTemplateFlowId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime Dated { get; set; }
        public string FIWNumber { get; set; }
        public string FIWSerial { get; set; }
        public int AdminUsersGroupId { get; set; }
        public int MemberUsersGroupId { get; set; }
        public int AuditorUsersGroupId { get; set; }
        public int BaseUserGroupId { get; set; }
        public int FolderId { get; set; }
        public int WorkspaceId { get; set; }
        public int BUnitId { get; set; }
        public int DivisionId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> DeactiavtionDate { get; set; }
    }
}
