//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FMSFileType
    {
        public int FileTypeId { get; set; }
        public string TypeName { get; set; }
        public string TypeShortName { get; set; }
        public string Extension { get; set; }
        public string Icon { get; set; }
        public string IconUrl { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
    }
}
