//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoldersLibrary
    {
        public int FolderId { get; set; }
        public string FolderGuid { get; set; }
        public string FolderName { get; set; }
        public string FolderDescription { get; set; }
        public string FolderPath { get; set; }
        public string ParentGuid { get; set; }
        public Nullable<bool> IsSystemFolder { get; set; }
        public Nullable<int> FileTypeId { get; set; }
        public Nullable<decimal> FileSize { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<bool> isFolder { get; set; }
        public string Extension { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<int> Extra1 { get; set; }
        public Nullable<bool> Extra2 { get; set; }
        public string Extra3 { get; set; }
        public string FolderIcon { get; set; }
    }
}
