//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleMarker
    {
        public int Id { get; set; }
        public string MarkName { get; set; }
        public string MarkTitle { get; set; }
        public string MarkDesc { get; set; }
        public string MarkLan { get; set; }
        public string MarkLat { get; set; }
        public string MarkValue { get; set; }
        public int CompanyId { get; set; }
        public int DivisionId { get; set; }
        public int BunitId { get; set; }
        public int ProjectId { get; set; }
        public int WorkSpaceId { get; set; }
        public int ProcessId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> TargetObjectId { get; set; }
        public Nullable<int> TargetTypeId { get; set; }
    }
}
