//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpactsT
    {
        public int Id { get; set; }
        public string ImpactName { get; set; }
        public string ImpactTitle { get; set; }
        public Nullable<int> ImpactValue { get; set; }
        public Nullable<int> ImpactPNegative { get; set; }
        public Nullable<int> ProcessTypeId { get; set; }
        public Nullable<int> ProcessMasterId { get; set; }
        public string ProcessGUID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> WorkSpaceId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
    }
}
