//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionConfidence_Lockup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public int CompanyId { get; set; }
        public int ProcessId { get; set; }
        public int BUnitId { get; set; }
        public int DivisionId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Dated { get; set; }
    }
}
