//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MainRiskManagment
    {
        public int Id { get; set; }
        public string RefNo { get; set; }
        public string ORA_No { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Tag_No { get; set; }
        public Nullable<bool> Sec { get; set; }
        public string RiskAssessTeam { get; set; }
        public string OperationalCondition { get; set; }
        public string OperationalRisk { get; set; }
        public Nullable<System.DateTime> AssessmentDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Expirydate { get; set; }
        public string ClouserApproval { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> ClouserDate { get; set; }
        public string ExtensionJustification { get; set; }
        public string NewSolution { get; set; }
        public string LocationTeamLeadApproval { get; set; }
        public string OperationalManagerApproval { get; set; }
        public Nullable<System.DateTime> NewExpiryDate { get; set; }
        public string OverallRisk { get; set; }
        public string RelatedORA { get; set; }
        public string RelatedReports { get; set; }
        public string ContingencyPlan { get; set; }
        public string ORATeamLeaderApproval { get; set; }
        public string AssessmentApproval { get; set; }
        public string TechnicalAuthorityApproval { get; set; }
        public string PermenetSolution { get; set; }
        public string SolutionOwnerNameSign { get; set; }
        public Nullable<bool> InProgress { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
