//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapLongLat
    {
        public string Code { get; set; }
        public string Code2 { get; set; }
        public string Code3 { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
    }
}
