//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixT
    {
        public int MatrixId { get; set; }
        public string MatrixName { get; set; }
        public int MatrixTypeId { get; set; }
        public int ProcessId { get; set; }
        public int CompanyId { get; set; }
        public int BUnitId { get; set; }
        public int DimX { get; set; }
        public int DimY { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Dated { get; set; }
        public string MatrixTitle { get; set; }
        public string MatrixDesc { get; set; }
    }
}
