//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatrixDetail
    {
        public int Id { get; set; }
        public int MatrixTId { get; set; }
        public Nullable<int> Col0 { get; set; }
        public string Col0Title { get; set; }
        public Nullable<double> Col0Val { get; set; }
        public Nullable<int> Col1Index { get; set; }
        public string Col1Title { get; set; }
        public Nullable<double> Col1Val { get; set; }
        public Nullable<int> Col2Index { get; set; }
        public string Col2Title { get; set; }
        public Nullable<double> Col2Val { get; set; }
        public Nullable<int> Col3Index { get; set; }
        public string Col3Title { get; set; }
        public Nullable<int> Col3Val { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
    }
}
