//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public MenuItem()
        {
            this.MenuItem1 = new HashSet<MenuItem>();
        }
    
        public int MenuItemId { get; set; }
        public string Text { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public Nullable<bool> Selected { get; set; }
        public string Iclass { get; set; }
        public Nullable<int> ParentId { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<bool> HasLink { get; set; }
        public string aClass { get; set; }
        public Nullable<int> rid { get; set; }
        public string vw { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public Nullable<bool> IsUser { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> IsExtra1 { get; set; }
        public Nullable<int> IsExtra2 { get; set; }
        public string IsExtra3 { get; set; }
    
        public virtual ICollection<MenuItem> MenuItem1 { get; set; }
        public virtual MenuItem MenuItem2 { get; set; }
    }
}
