//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationLockup
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public string IconClass { get; set; }
        public string Tag { get; set; }
        public Nullable<int> TypeId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public bool IsEscalatable { get; set; }
        public bool IsMentionDueDate { get; set; }
        public string RedirectController { get; set; }
        public string RedirectAction { get; set; }
        public string RedirectExtraParam { get; set; }
        public string RedirectExParam1 { get; set; }
        public string RedirectExParam2 { get; set; }
        public string RedirectExParam3 { get; set; }
        public string RedirectExParamDefault { get; set; }
    }
}
