//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationPriority_Lockup
    {
        public int Id { get; set; }
        public string Prioirity { get; set; }
        public string Icon { get; set; }
        public string IconClass { get; set; }
        public Nullable<int> EscalationInterval { get; set; }
        public Nullable<int> ReminerFrequency { get; set; }
        public Nullable<int> Ex1 { get; set; }
        public string Ex2 { get; set; }
        public Nullable<int> LifetimeInDays { get; set; }
        public Nullable<int> ExtensionsAllowed { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
