//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationLockup
    {
        public int Id { get; set; }
        public Nullable<int> value { get; set; }
        public string Command { get; set; }
        public bool IsDeleted { get; set; }
        public string Comment { get; set; }
        public bool IsActive { get; set; }
    }
}
