//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentRegistration
    {
        public int Id { get; set; }
        public string Customer_Id { get; set; }
        public string Store { get; set; }
        public string Terminal { get; set; }
        public string Channel { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public string Order_Id { get; set; }
        public string Order_Name { get; set; }
        public string Order_Info { get; set; }
        public string Transaction_Hint { get; set; }
        public string Return_Path { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Transaction_id { get; set; }
        public string Payment_portal { get; set; }
        public Nullable<int> Response_Code { get; set; }
        public string Response_Description { get; set; }
        public string Unique_Id { get; set; }
    }
}
