//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessMaster
    {
        public int Id { get; set; }
        public string GUID { get; set; }
        public string Number { get; set; }
        public string Serial { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string DescriptionRev { get; set; }
        public int UserId { get; set; }
        public int OwnerId { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public Nullable<int> COwnerId { get; set; }
        public Nullable<int> ClosingUserId { get; set; }
        public Nullable<int> RefProcessId { get; set; }
        public string RefProcessNo { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> SubLocationId { get; set; }
        public string LocationTxt { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateExtension { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public int FlowTypeId { get; set; }
        public int ProcessStructCoreId { get; set; }
        public int PriorityId { get; set; }
        public int ComplexityId { get; set; }
        public int CostRangeId { get; set; }
        public Nullable<decimal> CostBasic { get; set; }
        public Nullable<decimal> CostFinal { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string EquipmentTag { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public double StatusPercent { get; set; }
        public int StatusVal { get; set; }
        public string RClassA { get; set; }
        public string RClassB { get; set; }
        public string RClassC { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> WorkSpaceId { get; set; }
        public Nullable<bool> Mark { get; set; }
        public Nullable<int> MarkSeq { get; set; }
        public string MarkLogo { get; set; }
        public string RootId { get; set; }
        public bool IsTemp { get; set; }
        public Nullable<int> ExtensionTypeId { get; set; }
        public bool IsKey { get; set; }
        public bool RenderInLine { get; set; }
        public bool RenderAutoOpen { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public bool IsSubmitted { get; set; }
        public Nullable<System.DateTime> DateReviewed { get; set; }
        public bool IsReviewed { get; set; }
        public bool IsActive { get; set; }
        public int IsPosted { get; set; }
        public Nullable<int> Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string Taggs { get; set; }
        public string UserTaggs { get; set; }
        public Nullable<int> TotalSuccess { get; set; }
        public Nullable<int> TotalFailure { get; set; }
        public Nullable<int> TotalNeurtal { get; set; }
        public Nullable<int> TotalVoteLike { get; set; }
        public Nullable<int> TotalVoteDislike { get; set; }
        public Nullable<int> TotalActiveActionUnits { get; set; }
        public Nullable<int> TotalActiveActionUnitsCompleted { get; set; }
        public Nullable<int> TotalActiveSections { get; set; }
        public Nullable<int> TotalActiveSectionsCompleted { get; set; }
        public Nullable<int> TotalActiveStages { get; set; }
        public Nullable<int> TotalActiveStagesCompleted { get; set; }
        public Nullable<int> FolderId { get; set; }
        public Nullable<int> FinalStatusId { get; set; }
        public Nullable<int> FlowStatusId { get; set; }
        public Nullable<int> ActiveStageId { get; set; }
        public Nullable<int> ActiveSectionId { get; set; }
        public Nullable<int> ActiveActionUnitId { get; set; }
        public Nullable<bool> IsTimerStarted { get; set; }
        public Nullable<System.DateTime> TimerStartDatetime { get; set; }
        public Nullable<int> TimerStartingUnitId { get; set; }
        public Nullable<bool> IsTimerTopped { get; set; }
        public Nullable<System.DateTime> TimerStopDatetime { get; set; }
        public Nullable<int> TimerStopUnitId { get; set; }
        public int DefineNewTemplateId { get; set; }
        public int PreviewTemplateId { get; set; }
        public int WizardTemplateId { get; set; }
        public int WizardRevTemplateId { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public bool extraBit1 { get; set; }
        public int extraNum1 { get; set; }
        public double extraNum2 { get; set; }
        public string extraString { get; set; }
    }
}
