//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessFieldSetup
    {
        public int Id { get; set; }
        public int ColumnId { get; set; }
        public int ProcessId { get; set; }
        public int TableId { get; set; }
        public bool ShowHide { get; set; }
        public string DefaultValue { get; set; }
        public bool ManOptional { get; set; }
        public string DefaultInt { get; set; }
        public string ExtraText { get; set; }
        public string ExtraInt { get; set; }
        public bool Enabled { get; set; }
        public Nullable<int> ProcessWFlowId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> ExtraNumber { get; set; }
        public int DefaultNumericValue { get; set; }
        public int DefaultOptionsTypeListId { get; set; }
        public int ExtraNumberZero { get; set; }
        public string FieldLabelName { get; set; }
    }
}
