//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsT
    {
        public int ProjectId { get; set; }
        public string Number { get; set; }
        public string Serial { get; set; }
        public string GUID { get; set; }
        public int Type { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int ParentId { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public int UserId { get; set; }
        public int OwnerId { get; set; }
        public int finalstatusId { get; set; }
        public string Logo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string State { get; set; }
        public string CountryId { get; set; }
        public Nullable<int> adminGroup { get; set; }
        public string AdminUserList { get; set; }
        public string AdminUserListIds { get; set; }
        public string MemberUserList { get; set; }
        public string MemberUserListIds { get; set; }
        public string AuditorUserList { get; set; }
        public string AuditorUserListIds { get; set; }
        public int Account { get; set; }
        public int StatusVal { get; set; }
        public double StatusPercent { get; set; }
        public int BUnitId { get; set; }
        public int DivisionId { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public bool IsPosted { get; set; }
        public System.DateTime Dated { get; set; }
        public Nullable<int> WorkSpaceId { get; set; }
        public Nullable<int> FolderId { get; set; }
        public int PriorityId { get; set; }
        public int ComplexityId { get; set; }
        public int CostRangeId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string Taggs { get; set; }
        public Nullable<decimal> CostBasic { get; set; }
        public Nullable<decimal> CostFinal { get; set; }
        public string UserTaggs { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> SubLocationId { get; set; }
        public string LocationTxt { get; set; }
    }
}
