//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTDetail
    {
        public int Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string ProjectGuid { get; set; }
        public Nullable<System.DateTime> DateOfUpdate { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UserGuid { get; set; }
        public Nullable<int> Percentage { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public Nullable<bool> IsNotify { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> IsExtra { get; set; }
        public string IsExtra2 { get; set; }
    }
}
