//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireScoring
    {
        public int Id { get; set; }
        public int QMasterId { get; set; }
        public string QMasterGIUD { get; set; }
        public string QdQuestionIdList { get; set; }
        public int SelectionOption { get; set; }
        public string ResultMessage { get; set; }
        public string ResultURL { get; set; }
        public Nullable<int> WorkSpaceId { get; set; }
        public int OrderId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
    }
}
