//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireGroup
    {
        public int QGId { get; set; }
        public int QMasterId { get; set; }
        public string QGroupName { get; set; }
        public string QGroupDesc { get; set; }
        public string QGroupIcon { get; set; }
        public Nullable<int> QGroupOrder { get; set; }
        public string QGroupExtraTxt { get; set; }
        public Nullable<int> QGroupExtraInt { get; set; }
        public bool IsDeleted { get; set; }
    }
}
