//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireMasterA
    {
        public int QMasterId { get; set; }
        public string QNumber { get; set; }
        public string QSerial { get; set; }
        public string QMasterGUID { get; set; }
        public Nullable<int> QMasterOriginalRecordId { get; set; }
        public string QMasterOriginalRecordGUID { get; set; }
        public string Logo { get; set; }
        public Nullable<int> QOrder { get; set; }
        public string QTitle { get; set; }
        public string QDescription { get; set; }
        public Nullable<int> QFolderId { get; set; }
        public string QAnswerS { get; set; }
        public string QAnswerSTitle { get; set; }
        public string QAnswerL { get; set; }
        public string QAnswerLTitle { get; set; }
        public Nullable<int> QAnswerVal { get; set; }
        public string QAnswerValTitle { get; set; }
        public bool IsAutoVR { get; set; }
        public string RevAnswerS { get; set; }
        public string RevAnswerSTitle { get; set; }
        public string RevAnswerL { get; set; }
        public string RevAnswerLTitle { get; set; }
        public Nullable<int> RevAnswerVal { get; set; }
        public string RevAnswerValTitle { get; set; }
        public bool ForceAnalize { get; set; }
        public bool AllowAnalize { get; set; }
        public int OptimalValue { get; set; }
        public string OptimalValueTitle { get; set; }
        public string OptimalShort { get; set; }
        public string OptimalShortTitle { get; set; }
        public string OptimalLong { get; set; }
        public string OptimalLongTitle { get; set; }
        public bool QShowYesNo { get; set; }
        public bool QShowMaybe { get; set; }
        public bool QShowShortA { get; set; }
        public bool QShowLongA { get; set; }
        public bool QIsMandVal { get; set; }
        public bool IsMandYesNo { get; set; }
        public bool IsMandShortA { get; set; }
        public bool IsMandLongA { get; set; }
        public bool RevShowYesNo { get; set; }
        public bool RevShowShortR { get; set; }
        public bool RevShowLongR { get; set; }
        public bool IsMandYesNoRev { get; set; }
        public bool IsMandShortRev { get; set; }
        public bool IsMandLongRev { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Dated { get; set; }
        public Nullable<System.DateTime> DateAnswered { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsReviewed { get; set; }
        public Nullable<System.DateTime> DateReviewed { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public Nullable<int> DefaultRevUserGroup { get; set; }
        public bool IsValid { get; set; }
        public bool IsInvalid { get; set; }
        public string ReviewerNote { get; set; }
        public bool IsDefault { get; set; }
        public bool AllowFile { get; set; }
        public bool AllowLink { get; set; }
        public Nullable<int> TotalQuestions { get; set; }
        public int TotalValid { get; set; }
        public int TotalInvalid { get; set; }
        public int TotalAnswersMand { get; set; }
        public int TotalAnswersOpt { get; set; }
        public string FileGUID { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public bool IsSubmitted { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<int> ActionUnitId { get; set; }
        public Nullable<int> ProcessFlowId { get; set; }
        public Nullable<int> ProcessMasterId { get; set; }
        public string ProcessMasterGUID { get; set; }
        public Nullable<int> PossitiveQutaSuccess { get; set; }
        public Nullable<int> NegativeQutaSuccess { get; set; }
        public Nullable<bool> IsSuccesful { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<int> FinalResult { get; set; }
        public Nullable<decimal> FinalResultAverage { get; set; }
        public Nullable<decimal> ValidityAverage { get; set; }
        public Nullable<decimal> InValidityAverage { get; set; }
        public Nullable<int> TotalAppoved { get; set; }
        public Nullable<int> TotalRejected { get; set; }
        public Nullable<decimal> ApprovedAverage { get; set; }
        public Nullable<decimal> RejectedAverage { get; set; }
        public Nullable<bool> IsScoreEnabled { get; set; }
        public Nullable<int> IsScoreExtraInt { get; set; }
        public string IsScoreExtraTxt { get; set; }
    }
}
