//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubRiskManagement
    {
        public int Id { get; set; }
        public Nullable<int> MainRiskID { get; set; }
        public string Hazard { get; set; }
        public string HazardEffect { get; set; }
        public string RiskEval_HE { get; set; }
        public string RiskEval_P { get; set; }
        public string RiskEval_R { get; set; }
        public string ControlMeaurse { get; set; }
        public string SPA { get; set; }
        public string RiskResidual_HE { get; set; }
        public string RiskResidual_P { get; set; }
        public string RiskResidual_R { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
