//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemProcessT
    {
        public int Id { get; set; }
        public string GUID { get; set; }
        public string SystemProcessName { get; set; }
        public string SystemProcessTitle { get; set; }
        public string SystemProcessDescription { get; set; }
        public int SystemProcessDefaultTemplateId { get; set; }
        public string SystemProcessDefaultTemplateGUID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public int CompanyId { get; set; }
        public int DivisionId { get; set; }
        public int BUnitId { get; set; }
        public Nullable<int> RootProcessId { get; set; }
        public string Extra { get; set; }
    }
}
