//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemProcessRootT
    {
        public int ID { get; set; }
        public string Guid { get; set; }
        public string RootProcessName { get; set; }
        public string RootProcessDesc { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ExtraId { get; set; }
        public string ExtraText { get; set; }
    }
}
