//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TourT
    {
        public int Id { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<int> TargetOrder { get; set; }
        public string TargetClass { get; set; }
        public string TargetClass1 { get; set; }
        public string TargetClass2 { get; set; }
        public string TargetFunction { get; set; }
        public string TargetSubject { get; set; }
        public string TargetDesc { get; set; }
        public string TargetIconUrl { get; set; }
        public string TargetUrl { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public string placement { get; set; }
        public string TargetSubjectAr { get; set; }
        public string TargetDescAr { get; set; }
        public string TargetIconUrlAr { get; set; }
        public string BackgroudImg { get; set; }
        public string VideoUrl { get; set; }
        public string ExtraText { get; set; }
        public Nullable<int> ExtraInt1 { get; set; }
        public Nullable<int> ExtraInt2 { get; set; }
        public bool ExtraBit1 { get; set; }
        public bool ExtraBit2 { get; set; }
    }
}
