//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.UsersInGroups = new HashSet<UsersInGroup>();
        }
    
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public string GroupDesc { get; set; }
        public string GroupLogo { get; set; }
        public Nullable<int> GroupMembers { get; set; }
        public Nullable<int> AccountId { get; set; }
        public int CompanyId { get; set; }
        public int DivisionId { get; set; }
        public int BUnitId { get; set; }
        public Nullable<int> ParentGroupId { get; set; }
        public Nullable<int> CollectiveGroupId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime Dated { get; set; }
    
        public virtual ICollection<UsersInGroup> UsersInGroups { get; set; }
    }
}
