//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPrivilegeT
    {
        public int PrivilegeId { get; set; }
        public int GroupId { get; set; }
        public bool IsAdmin { get; set; }
        public bool IsMember { get; set; }
        public bool IsManager { get; set; }
        public bool IsAuditor { get; set; }
        public bool IsSubscriber { get; set; }
        public int WorkSpaceId { get; set; }
        public int ProjectId { get; set; }
        public int ProcessId { get; set; }
        public int BUnitId { get; set; }
        public int DivisionId { get; set; }
        public int CompanyId { get; set; }
        public Nullable<int> TargetTypeId { get; set; }
        public Nullable<int> TargetObjectId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime Dated { get; set; }
        public Nullable<System.DateTime> SubscriptionDate { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public Nullable<System.DateTime> DeActivationDate { get; set; }
        public bool CanRead { get; set; }
        public bool CanAdd { get; set; }
        public bool CanEdit { get; set; }
        public bool CanPost { get; set; }
        public bool CanUnpost { get; set; }
        public bool CanDelete { get; set; }
        public bool CanRestore { get; set; }
        public bool CanSearch { get; set; }
        public bool CanManage { get; set; }
        public bool CanActivate { get; set; }
        public bool CanDeactivate { get; set; }
        public bool CanUpload { get; set; }
        public bool CanDownload { get; set; }
        public bool AllowIntro { get; set; }
        public bool AllowIntroOpen { get; set; }
        public bool AllowProjects { get; set; }
        public bool AllowProjectsOpen { get; set; }
        public bool AllowProcess { get; set; }
        public bool AllowProcessOpen { get; set; }
        public bool AllowFiles { get; set; }
        public bool AllowFilesOpen { get; set; }
        public bool AllowUsers { get; set; }
        public bool AllowUsersOpen { get; set; }
        public bool AllowLog { get; set; }
        public bool AllowLogOpen { get; set; }
        public bool AllowCharts { get; set; }
        public bool AllowChartsOpen { get; set; }
        public bool AllowExtra { get; set; }
        public bool AllowExtraOpen { get; set; }
        public bool AllowWorkSpaces { get; set; }
        public bool AllowWorkSpacesOpen { get; set; }
        public bool AllowDelegation { get; set; }
        public bool AllowDelegationOpen { get; set; }
        public bool AllowChilds { get; set; }
        public bool AllowChildsOpen { get; set; }
        public bool AllowGalary { get; set; }
        public bool AllowGalaryOpen { get; set; }
        public bool AllowFeeds { get; set; }
        public bool AllowFeedsOpen { get; set; }
        public bool AllowStatistics { get; set; }
        public bool AllowStatisticOpen { get; set; }
        public bool AllowEx1 { get; set; }
        public bool AllowEx1Open { get; set; }
        public bool AllowEx2 { get; set; }
        public bool AllowEx2Open { get; set; }
        public bool AllowSummary { get; set; }
        public bool AllowSummaryOpen { get; set; }
        public int ExtraField1 { get; set; }
        public Nullable<int> ExtraField2 { get; set; }
        public bool AllowLocation { get; set; }
        public bool AllowCategory { get; set; }
        public bool AllowComplexity { get; set; }
        public bool AllowPriority { get; set; }
        public bool AllowSetting1 { get; set; }
        public bool AllowSetting2 { get; set; }
        public int AllowSetting3 { get; set; }
        public string AllowSetting4 { get; set; }
    }
}
