//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInHirarchy
    {
        public int Id { get; set; }
        public Nullable<int> LeaderId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<int> DevId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> WorkspaceId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> ProcessTempateId { get; set; }
        public Nullable<int> ExtraId { get; set; }
        public Nullable<int> UserLevelId { get; set; }
        public string ExtraText { get; set; }
        public Nullable<int> GroupId { get; set; }
    }
}
