//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VotesXT
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Serial { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public int OriginatorId { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public string ParticipantsIdList { get; set; }
        public string ParticipantsList { get; set; }
        public int StatusId { get; set; }
        public int Progress { get; set; }
        public int SuccessQuota { get; set; }
        public Nullable<int> FailureQuota { get; set; }
        public Nullable<int> TotalVoteLike { get; set; }
        public Nullable<int> TotalVoteDissLike { get; set; }
        public Nullable<int> TotalVoteNA { get; set; }
        public Nullable<int> TotalVotes { get; set; }
        public Nullable<int> ActionId { get; set; }
        public int ProcessId { get; set; }
        public int ProjectId { get; set; }
        public int BUnitId { get; set; }
        public int DivisionId { get; set; }
        public int CompanyId { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateRaised { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public System.DateTime DateModified { get; set; }
    }
}
