//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ActionTA_Row
    {
        public int actionUnitId { get; set; }
        public string actionUnitName { get; set; }
        public string Title { get; set; }
        public string Logo { get; set; }
        public int ActionTId { get; set; }
        public int ActionUserGroupId { get; set; }
        public string GroupName { get; set; }
        public int ActionUserId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public string ActionComment { get; set; }
        public int RecordStatus { get; set; }
        public System.DateTime Dated { get; set; }
        public string ActionUserInitial { get; set; }
        public Nullable<int> FlowSequence { get; set; }
        public Nullable<int> ResultCall { get; set; }
        public int IsPosted { get; set; }
        public int VoteUp { get; set; }
        public string VoteUpList { get; set; }
        public int VoteDown { get; set; }
        public string VoteDownList { get; set; }
        public string ActionLog { get; set; }
        public Nullable<bool> Mark { get; set; }
        public Nullable<int> MarkSeq { get; set; }
        public string MarkLogo { get; set; }
        public bool IsMandatory { get; set; }
        public int RenderInLine { get; set; }
        public int RenderAutoOpen { get; set; }
        public int IsKeyUnit { get; set; }
        public bool IsKey { get; set; }
        public Nullable<int> ActionUserDelId { get; set; }
        public string DelegateUserName { get; set; }
        public Nullable<int> ActionUserTempId { get; set; }
        public string TempUserName { get; set; }
        public bool GRenderInline { get; set; }
        public bool GRenderAuto { get; set; }
        public int ProcessId { get; set; }
        public int StageId { get; set; }
        public int SectionId { get; set; }
        public int CompanyId { get; set; }
        public int BUnitId { get; set; }
        public int DevisionId { get; set; }
        public int ConformId { get; set; }
        public string ConformText { get; set; }
        public Nullable<int> IsRouted { get; set; }
        public Nullable<int> IsDelegated { get; set; }
        public Nullable<int> IsRecycled { get; set; }
        public Nullable<int> IsHold { get; set; }
        public Nullable<int> IsExtra1 { get; set; }
        public Nullable<int> IsExtra2 { get; set; }
        public Nullable<int> PrevActionId { get; set; }
        public string PrevActionUnit { get; set; }
        public Nullable<int> NextActionId { get; set; }
        public string NextActionUnit { get; set; }
        public string FlowSerial { get; set; }
        public string SerialFrom { get; set; }
        public string SerialTo { get; set; }
        public Nullable<int> IsRemind { get; set; }
        public Nullable<int> IsCancel { get; set; }
        public Nullable<int> IsUndo { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> IsClose { get; set; }
        public bool IsStarting { get; set; }
        public bool IsClosing { get; set; }
        public bool IsCompleted { get; set; }
        public bool AllowClose { get; set; }
        public bool AllowCancel { get; set; }
        public bool AllowHold { get; set; }
        public bool AllowRoute { get; set; }
        public bool AllowDelegate { get; set; }
        public bool AllowRemind { get; set; }
        public bool AllowRecycle { get; set; }
        public bool AllowAudit { get; set; }
        public bool AllowChangeGroup { get; set; }
        public bool AllowChangeUser { get; set; }
        public Nullable<int> FolderId { get; set; }
        public Nullable<int> QuestionaireMasterId { get; set; }
        public bool IsQuestionaire { get; set; }
        public bool IsQuestionaireRequired { get; set; }
        public bool IsQuestionaireCompleted { get; set; }
        public Nullable<int> QuestionaireMasterIdA { get; set; }
        public Nullable<int> QuestionaireUserGroupIdRev { get; set; }
        public string QTitle { get; set; }
        public string QuesUserGroupName { get; set; }
        public string QMasterAGIUD { get; set; }
        public string UserGUID { get; set; }
        public string UserInitial { get; set; }
        public string UserPic { get; set; }
        public string DelGUID { get; set; }
        public string DelInitial { get; set; }
        public string Delpic { get; set; }
        public bool IsActive { get; set; }
        public bool IsSkipped { get; set; }
        public Nullable<int> AutoSequence { get; set; }
        public string PrevActionUnitSerial { get; set; }
        public string NextActionUnitSerial { get; set; }
        public string QSerial { get; set; }
        public Nullable<bool> QIsSubmitted { get; set; }
        public Nullable<bool> QIsReviewed { get; set; }
        public Nullable<bool> QIsSuccesful { get; set; }
        public Nullable<bool> QIsCompleted { get; set; }
        public bool ShowNotApplicable { get; set; }
        public bool ShowAgree { get; set; }
        public bool ShowDisagree { get; set; }
        public bool IsTimerStart { get; set; }
        public Nullable<System.DateTime> TimerStartDatetime { get; set; }
        public bool IsTimerStop { get; set; }
        public Nullable<System.DateTime> TimerStopDatetime { get; set; }
        public bool IsJumper { get; set; }
        public int JumptoUnitId { get; set; }
        public bool IsMandatoryToggleable { get; set; }
        public string Expr1 { get; set; }
        public string QDescription { get; set; }
        public string OptimalShort { get; set; }
        public string OptimalLong { get; set; }
        public Nullable<int> NegativeQutaSuccess { get; set; }
        public Nullable<int> PossitiveQutaSuccess { get; set; }
        public bool IsTaskEnabled { get; set; }
        public bool NotifyLocationUsersInfo { get; set; }
        public bool NotifyLocationUsersAction { get; set; }
        public bool NotifyInfoTaskCompletedThis { get; set; }
        public bool NotifyInfoTaskCompletedPrev { get; set; }
        public bool NotifyActionTaskCompletedThis { get; set; }
        public bool NotifyActionTaskCompletedPrev { get; set; }
        public bool NotifyActionTaskCompletedAll { get; set; }
        public bool ExtraBit1 { get; set; }
        public int ExtraSetting { get; set; }
        public string IsHirarchyExtra { get; set; }
    }
}
