//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Delegation_
    {
        public int Id { get; set; }
        public System.DateTime DateFrom { get; set; }
        public System.DateTime DateTo { get; set; }
        public int CompanyId { get; set; }
        public int DivisionId { get; set; }
        public int BUnitID { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public int ProcessFlowTypeId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> ProcessCount { get; set; }
        public Nullable<int> ActionUnitCounts { get; set; }
        public string Comment { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime Dated { get; set; }
        public bool IsAutoExpire { get; set; }
        public bool IsNotifyOwnerOnChange { get; set; }
        public string UserFromName { get; set; }
        public string UserFromEmail { get; set; }
        public string UserToName { get; set; }
        public string UserToEmail { get; set; }
        public int UserFormId { get; set; }
        public int UserToId { get; set; }
        public string UserFromPic { get; set; }
        public string UserToPic { get; set; }
    }
}
