//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_FlowsInWorkSpaces_Search
    {
        public int WorkSpaceId { get; set; }
        public string WorspaceNumber { get; set; }
        public string WorspaceSerial { get; set; }
        public string WorspaceTitle { get; set; }
        public string FlowName { get; set; }
        public string FlowAbbr { get; set; }
        public string FlowDesc { get; set; }
        public string FlowTitle { get; set; }
        public string FlowLogo { get; set; }
        public int BUnitId { get; set; }
        public string BUnitAbbr { get; set; }
        public string BUnitName { get; set; }
        public string WorspaceLogo { get; set; }
        public int FlowId { get; set; }
        public string RClassA { get; set; }
        public string RClassB { get; set; }
        public string RClassC { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public int fiwId { get; set; }
        public System.DateTime fiwDate { get; set; }
        public bool fiwIsActive { get; set; }
        public bool fiwIsDeleted { get; set; }
        public string FIWNumber { get; set; }
        public string FIWSerial { get; set; }
        public int FIWAdminUsersGroupId { get; set; }
        public int FIWMemberUsersGroupId { get; set; }
        public int FIWAuditorUsersGroupId { get; set; }
        public int FIWBaseUserGroupId { get; set; }
        public int FIWFolderId { get; set; }
        public int CustomFlowId { get; set; }
        public int OriginalTemplateFlowId { get; set; }
        public string WorkGUID { get; set; }
        public string BUnitGUID { get; set; }
        public string ProcGUID { get; set; }
        public Nullable<bool> IsSelectionQuestionnaire { get; set; }
        public Nullable<int> ScoringQuestionnaireId { get; set; }
    }
}
