//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Master_Process
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Serial { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int OwnerId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> RefProcessId { get; set; }
        public string RefProcessNo { get; set; }
        public int LocationId { get; set; }
        public string Location { get; set; }
        public Nullable<int> SubLocationId { get; set; }
        public string SubLocation { get; set; }
        public string LocationTxt { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public int CategoryId { get; set; }
        public double StatusPercent { get; set; }
        public int StatusVal { get; set; }
        public string RClassA { get; set; }
        public string RClassB { get; set; }
        public string RClassC { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<bool> Mark { get; set; }
        public Nullable<int> MarkSeq { get; set; }
        public string MarkLogo { get; set; }
        public string RootId { get; set; }
        public bool IsKey { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public int IsPosted { get; set; }
        public string Category { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string SubCategory { get; set; }
        public int FlowTypeId { get; set; }
        public int ProcessStructCoreId { get; set; }
        public Nullable<int> WorkSpaceId { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public bool IsSubmitted { get; set; }
        public Nullable<System.DateTime> DateReviewed { get; set; }
        public bool IsReviewed { get; set; }
        public string GUID { get; set; }
        public string PeriodTypeText { get; set; }
        public string PeriodTypeClass { get; set; }
        public string PeriodTypeClass2 { get; set; }
        public bool IsTemp { get; set; }
        public Nullable<int> ExtensionTypeId { get; set; }
    }
}
