//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_NotificaionFeeds
    {
        public Nullable<int> TypeId { get; set; }
        public int NotificationId { get; set; }
        public string Name { get; set; }
        public string Icon { get; set; }
        public string IconClass { get; set; }
        public string Description { get; set; }
        public string DescClass { get; set; }
        public string Tag { get; set; }
        public string TagClass { get; set; }
        public Nullable<System.DateTime> DateSince { get; set; }
        public string DateClass { get; set; }
        public string RecController { get; set; }
        public string RecAction { get; set; }
        public Nullable<int> Param { get; set; }
        public string Extra1 { get; set; }
        public string Extra2 { get; set; }
        public Nullable<int> EmailRef { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> ActionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public Nullable<int> PriorityId { get; set; }
        public int statusVal { get; set; }
        public string StatusTxt { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string StatusClass { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public string UserTaggs { get; set; }
        public string Subject { get; set; }
        public Nullable<int> UserFlag { get; set; }
        public Nullable<System.DateTime> UserFlagDate { get; set; }
        public Nullable<System.DateTime> UserCompletionDate { get; set; }
        public string UserResponse { get; set; }
        public Nullable<int> OriginatorId { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public string UserPic { get; set; }
        public string OriginatorName { get; set; }
        public string OriginatorPic { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string NotificationSubject { get; set; }
        public string NotificationBody { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool IsRead { get; set; }
        public Nullable<System.DateTime> ReadDateTime { get; set; }
        public bool IsAttachement { get; set; }
        public bool IsStar { get; set; }
        public Nullable<int> ReplyForENotificationId { get; set; }
        public bool IsSentPending { get; set; }
        public bool IsSent { get; set; }
        public Nullable<System.DateTime> SentDateTime { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public bool IsDraft { get; set; }
        public bool IsSpamJunk { get; set; }
        public string Number { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public Nullable<int> CCUserId { get; set; }
        public Nullable<int> BCCUserId { get; set; }
        public int FromUserId { get; set; }
        public string Prioirity { get; set; }
        public string PrioIcon { get; set; }
        public string PrioClass { get; set; }
        public Nullable<int> IsActioned { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<int> SendingCounter { get; set; }
        public string ProcessNumber { get; set; }
        public string ActionNumber { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectGUID { get; set; }
        public string ProcessGUID { get; set; }
        public string NotificationGUID { get; set; }
        public Nullable<int> TargetRecordId { get; set; }
        public string TargetRecordSerial { get; set; }
        public string TargetRecordGUID { get; set; }
        public Nullable<int> TargetRecordType { get; set; }
        public bool IsMentionDueDate { get; set; }
        public Nullable<int> EscalationInterval { get; set; }
        public Nullable<int> ReminerFrequency { get; set; }
        public Nullable<bool> IsDissmissed { get; set; }
        public Nullable<System.DateTime> DissmissDate { get; set; }
        public Nullable<int> DissmisUserId { get; set; }
        public Nullable<int> DifferedCounter { get; set; }
        public Nullable<System.DateTime> DifferedDate { get; set; }
        public Nullable<int> DifferedUserId { get; set; }
        public Nullable<System.DateTime> NotificationDueDate { get; set; }
        public Nullable<int> EscalatedCounter { get; set; }
        public Nullable<System.DateTime> EscalatedDate { get; set; }
        public Nullable<int> EscalatedUserId { get; set; }
        public string RedirectController { get; set; }
        public string RedirectAction { get; set; }
        public string RedirectExtraParam { get; set; }
        public Nullable<bool> IsDelegated { get; set; }
        public Nullable<int> DelegationId { get; set; }
        public string DelegationSerial { get; set; }
        public string DelegationGUID { get; set; }
        public Nullable<int> IsOptionalKind { get; set; }
        public Nullable<bool> MailActions { get; set; }
        public Nullable<bool> MailInfo { get; set; }
        public Nullable<bool> MailExpiry { get; set; }
        public Nullable<bool> MailExtra { get; set; }
        public string OriginatorEmail { get; set; }
        public string OriginatorGUID { get; set; }
        public string RedirectExParam1 { get; set; }
        public string RedirectExParam2 { get; set; }
        public string RedirectExParam3 { get; set; }
        public string RedirectExParamDefault { get; set; }
        public string UserGUID { get; set; }
        public Nullable<int> WorkSpaceId { get; set; }
        public Nullable<int> ProcessStructureCoreId { get; set; }
        public Nullable<int> ExtraId { get; set; }
        public Nullable<int> ProcessTypeId { get; set; }
        public bool IsEscalatable { get; set; }
    }
}
