//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ProcessFlowA
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string Logo { get; set; }
        public int ParentId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> NextStepId { get; set; }
        public Nullable<int> PrevStepId { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public Nullable<int> FlowSequence { get; set; }
        public string FlowType { get; set; }
        public Nullable<int> FlowDirection { get; set; }
        public Nullable<int> DiectVal { get; set; }
        public string DirecText { get; set; }
        public Nullable<int> SuccessCondition { get; set; }
        public Nullable<int> SuccessVal { get; set; }
        public string successText { get; set; }
        public Nullable<int> SuccessValue { get; set; }
        public Nullable<int> FinalScore { get; set; }
        public string FlowSerial { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> ActionTID { get; set; }
        public System.DateTime Dated { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public string BUnitName { get; set; }
        public Nullable<int> DevisionVal { get; set; }
        public string DevisionText { get; set; }
        public bool IsMandatory { get; set; }
        public int IsPosted { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> Mark { get; set; }
        public Nullable<int> MarkSeq { get; set; }
        public string MarkLogo { get; set; }
        public bool IsKey { get; set; }
        public bool RenderInLine { get; set; }
        public bool RenderAutoOpen { get; set; }
        public string RClassA { get; set; }
        public string RClassB { get; set; }
        public string RClassC { get; set; }
        public bool Flag1 { get; set; }
        public bool Flag2 { get; set; }
        public bool Flag3 { get; set; }
        public bool Flag4 { get; set; }
        public bool Flag5 { get; set; }
        public string Abbr { get; set; }
        public int FlowCoreId { get; set; }
        public Nullable<int> FailureCondition { get; set; }
        public Nullable<int> SuccessActual { get; set; }
        public Nullable<int> FailureValue { get; set; }
        public Nullable<int> FailureActual { get; set; }
        public Nullable<int> SuccessValueMin { get; set; }
        public bool IsSkipped { get; set; }
        public int ActiveChildsCount { get; set; }
        public bool ShowNotApplicable { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public bool IsStarting { get; set; }
        public bool IsClosing { get; set; }
        public bool AllowClose { get; set; }
        public bool AllowCancel { get; set; }
        public bool AllowHold { get; set; }
        public bool AllowRoute { get; set; }
        public bool AllowDelegate { get; set; }
        public bool AllowRemind { get; set; }
        public bool AllowRecycle { get; set; }
        public bool AllowAudit { get; set; }
        public bool AllowChangeGroup { get; set; }
        public bool AllowChangeUser { get; set; }
        public Nullable<int> SupervisorGroupId { get; set; }
        public Nullable<int> SupervisorUserId { get; set; }
        public Nullable<int> SupervisorDelegateId { get; set; }
        public bool IsCompleted { get; set; }
        public Nullable<int> NeurtalValue { get; set; }
        public Nullable<int> NeurtalActual { get; set; }
        public string RecordStatusNote { get; set; }
        public Nullable<int> SuccessGoTo { get; set; }
        public Nullable<int> FailureGoTo { get; set; }
        public Nullable<int> IsSucessful { get; set; }
        public Nullable<int> FolderId { get; set; }
        public Nullable<int> QuestionaireMasterId { get; set; }
        public bool IsQuestionaire { get; set; }
        public bool IsQuestionaireRequired { get; set; }
        public bool IsQuestionaireCompleted { get; set; }
        public Nullable<int> QuestionaireUserGroupIdRev { get; set; }
        public bool Flag6 { get; set; }
        public bool Flag7 { get; set; }
        public bool Flag8 { get; set; }
        public bool Flag9 { get; set; }
        public bool Flag10 { get; set; }
        public bool Flag11 { get; set; }
        public bool Flag12 { get; set; }
        public bool Flag13 { get; set; }
        public bool Flag14 { get; set; }
        public bool Flag15 { get; set; }
        public bool IsOwnerAction { get; set; }
        public bool IsReviewerAction { get; set; }
        public Nullable<int> AutoSequence { get; set; }
        public bool ShowAgree { get; set; }
        public bool ShowDisagree { get; set; }
        public bool IsTimerStart { get; set; }
        public bool IsTimerStop { get; set; }
        public Nullable<System.DateTime> TimerStopDatetime { get; set; }
        public bool IsJumper { get; set; }
        public int JumptoUnitId { get; set; }
        public bool IsMandatoryToggleable { get; set; }
        public bool IsExtraBit { get; set; }
        public bool LockMasterFeatures { get; set; }
        public bool LockMasterFlow { get; set; }
        public Nullable<System.DateTime> TimerStartDatetime { get; set; }
        public Nullable<bool> IsSelectionQuestionnaire { get; set; }
        public Nullable<int> ScoringQuestionnaireId { get; set; }
        public Nullable<bool> IsHirarchyEnabled { get; set; }
        public Nullable<int> IsHirarchyDirection { get; set; }
        public string IsHirarchyExtra { get; set; }
        public bool IsTaskEnabled { get; set; }
        public bool NotifyLocationUsersInfo { get; set; }
        public bool NotifyLocationUsersAction { get; set; }
        public bool NotifyInfoTaskCompletedThis { get; set; }
        public bool NotifyInfoTaskCompletedPrev { get; set; }
        public bool NotifyActionTaskCompletedThis { get; set; }
        public bool NotifyActionTaskCompletedPrev { get; set; }
        public bool NotifyActionTaskCompletedAll { get; set; }
        public bool ExtraBit1 { get; set; }
        public int ExtraSetting { get; set; }
        public int ExtraNum1 { get; set; }
        public double ExtraNum2 { get; set; }
        public string ExtraString1 { get; set; }
        public string ExtraString2 { get; set; }
        public int DefineNewTemplateId { get; set; }
        public int PreviewTemplateId { get; set; }
        public int WizardTemplateId { get; set; }
        public int WizardRevTemplateId { get; set; }
    }
}
