//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Process_Exts
    {
        public int ProcessId { get; set; }
        public string Number { get; set; }
        public string Serial { get; set; }
        public string Title { get; set; }
        public Nullable<int> CountAllTasks { get; set; }
        public Nullable<int> CountPendingTasks { get; set; }
        public Nullable<int> CountClosedTasks { get; set; }
        public Nullable<int> CountRejectedTasks { get; set; }
        public Nullable<int> CountCanceledTasks { get; set; }
        public Nullable<int> CountOveDueTasks { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public Nullable<int> UserCountAllTasks { get; set; }
        public Nullable<int> UserCountPendingTasks { get; set; }
        public Nullable<int> UserCountClosedTasks { get; set; }
        public Nullable<int> UserCountRejectedTasks { get; set; }
        public Nullable<int> UserCountCanceledTasks { get; set; }
        public Nullable<int> UserCountOveDueTasks { get; set; }
        public int FlowTypeId { get; set; }
        public int ProcessStructCoreId { get; set; }
        public Nullable<int> ProjectId { get; set; }
    }
}
