//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ProcessUnits_QuestionnaireA
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Abbr { get; set; }
        public string Description { get; set; }
        public string Title { get; set; }
        public string Logo { get; set; }
        public int ParentId { get; set; }
        public int TypeId { get; set; }
        public Nullable<int> RecordStatus { get; set; }
        public string RecordStatusNote { get; set; }
        public Nullable<int> FlowSequence { get; set; }
        public string FlowType { get; set; }
        public Nullable<int> NeurtalActual { get; set; }
        public Nullable<int> FinalScore { get; set; }
        public string FlowSerial { get; set; }
        public string RClassA { get; set; }
        public string RClassB { get; set; }
        public string RClassC { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> ActionTID { get; set; }
        public System.DateTime Dated { get; set; }
        public bool IsMandatory { get; set; }
        public int IsPosted { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<bool> Mark { get; set; }
        public Nullable<int> MarkSeq { get; set; }
        public string MarkLogo { get; set; }
        public string RootId { get; set; }
        public Nullable<int> ActionUConformance { get; set; }
        public bool IsKey { get; set; }
        public Nullable<int> FlowMasterId { get; set; }
        public int FlowCoreId { get; set; }
        public bool IsSkipped { get; set; }
        public int ActiveChildsCount { get; set; }
        public bool ShowNotApplicable { get; set; }
        public bool IsStarting { get; set; }
        public bool IsClosing { get; set; }
        public bool AllowClose { get; set; }
        public bool AllowCancel { get; set; }
        public bool AllowHold { get; set; }
        public bool AllowRoute { get; set; }
        public bool AllowDelegate { get; set; }
        public bool AllowRemind { get; set; }
        public bool AllowRecycle { get; set; }
        public bool AllowAudit { get; set; }
        public bool AllowChangeGroup { get; set; }
        public bool AllowChangeUser { get; set; }
        public Nullable<int> SupervisorGroupId { get; set; }
        public Nullable<int> SupervisorUserId { get; set; }
        public Nullable<int> SupervisorDelegateId { get; set; }
        public Nullable<int> FolderId { get; set; }
        public Nullable<int> QuestionaireMasterId { get; set; }
        public bool IsQuestionaire { get; set; }
        public bool IsQuestionaireRequired { get; set; }
        public bool IsQuestionaireCompleted { get; set; }
        public string QuestionLogo { get; set; }
        public string QTitle { get; set; }
        public string QDescription { get; set; }
        public bool IsReviewed { get; set; }
        public bool IsValid { get; set; }
        public bool IsActive { get; set; }
        public int QMasterId { get; set; }
        public string ProcessMasterGUID { get; set; }
        public string ProcessMasterNumber { get; set; }
        public string ProcessMasterSerial { get; set; }
        public string ProcessMasterTitle { get; set; }
        public Nullable<System.DateTime> DateReviewed { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public bool IsSubmitted { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public Nullable<System.DateTime> DateSubmitted { get; set; }
        public Nullable<int> UserId { get; set; }
        public string QMasterGUID { get; set; }
        public string UserGUID { get; set; }
        public string UserName { get; set; }
        public string UserInitial { get; set; }
        public string UserPic { get; set; }
        public string RevUserGUID { get; set; }
        public string RevUserName { get; set; }
        public string RevUserInitial { get; set; }
        public string RevUserPic { get; set; }
        public string AutoText { get; set; }
        public bool IsAutoVR { get; set; }
        public Nullable<bool> IsCompleted { get; set; }
        public Nullable<bool> IsQSuccessful { get; set; }
        public string OptimalShort { get; set; }
        public string OptimalLong { get; set; }
        public Nullable<int> PossitiveQutaSuccess { get; set; }
        public Nullable<int> NegativeQutaSuccess { get; set; }
    }
}
