//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Project_Votes
    {
        public int ProjectId { get; set; }
        public string Number { get; set; }
        public string Title { get; set; }
        public Nullable<int> CountAllTasks { get; set; }
        public Nullable<int> CountPendingTasks { get; set; }
        public Nullable<int> CountClosedTasks { get; set; }
        public Nullable<int> CountRejectedTasks { get; set; }
        public Nullable<int> CountCanceledTasks { get; set; }
        public Nullable<int> CountOveDueTasks { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OriginatorId { get; set; }
        public string OriginatorName { get; set; }
        public int taskId { get; set; }
        public string UserName { get; set; }
    }
}
