//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_ProjectsT
    {
        public int ProjectId { get; set; }
        public string Number { get; set; }
        public string Serial { get; set; }
        public int Type { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int ParentId { get; set; }
        public int OwnerId { get; set; }
        public string Logo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string CountryId { get; set; }
        public Nullable<int> adminGroup { get; set; }
        public string AdminUserList { get; set; }
        public string AdminUserListIds { get; set; }
        public string MemberUserList { get; set; }
        public string MemberUserListIds { get; set; }
        public int Account { get; set; }
        public int StatusVal { get; set; }
        public double StatusPercent { get; set; }
        public int BUnitId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Dated { get; set; }
        public string OwnerName { get; set; }
        public string UserEmail { get; set; }
        public string UserTelephone { get; set; }
        public string UserMobile { get; set; }
        public string UserPic { get; set; }
        public string BUnitAbbr { get; set; }
        public string BUnitName { get; set; }
        public string AuditorUserList { get; set; }
        public string AuditorUserListIds { get; set; }
        public Nullable<int> WorkSpaceId { get; set; }
        public Nullable<int> FolderId { get; set; }
        public string WorkSpaceSerial { get; set; }
        public string WorSpaceTitle { get; set; }
        public string FolderName { get; set; }
        public string FolderPath { get; set; }
        public string OwnerGUID { get; set; }
        public string ProjGUID { get; set; }
        public int UserId { get; set; }
        public int finalstatusId { get; set; }
        public string UserGUID { get; set; }
        public string UserName { get; set; }
        public string FStauseText { get; set; }
        public string FStausClass { get; set; }
        public string FStausClass2 { get; set; }
        public string BUnitGUID { get; set; }
        public string WorkspaceGUID { get; set; }
        public string ProjectTypeText { get; set; }
        public string ProjectTypeClass { get; set; }
        public string ProjectTypeClass2 { get; set; }
        public int DivisionId { get; set; }
        public string DivAbbr { get; set; }
        public string DivGUID { get; set; }
        public string DivName { get; set; }
        public int CompanyId { get; set; }
        public string ComAbbr { get; set; }
        public string ComGUID { get; set; }
        public string ComName { get; set; }
        public int PriorityId { get; set; }
        public int ComplexityId { get; set; }
        public int CostRangeId { get; set; }
        public int CategoryId { get; set; }
        public string Taggs { get; set; }
        public Nullable<decimal> CostBasic { get; set; }
        public Nullable<decimal> CostFinal { get; set; }
        public string UserTaggs { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> SubLocationId { get; set; }
        public string LocationTxt { get; set; }
        public string LocationName { get; set; }
        public string SubLocation { get; set; }
        public string Category { get; set; }
        public string SubCategory { get; set; }
        public string PriorityName { get; set; }
        public string PriorityClass { get; set; }
        public string Complexityname { get; set; }
        public string ComplexityClass { get; set; }
        public string CostRangeName { get; set; }
        public string DivSerial { get; set; }
        public string ComSerial { get; set; }
        public string BUnitSerial { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateStart2 { get; set; }
        public System.DateTime DateEnd { get; set; }
        public System.DateTime DateEnd2 { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateCreated2 { get; set; }
        public System.DateTime DateModified { get; set; }
        public System.DateTime DateModified2 { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<System.DateTime> DateClosed2 { get; set; }
        public string State { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> ParentUnitUserGroupId { get; set; }
        public Nullable<int> PerentWSUserGroupId { get; set; }
    }
}
