//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Questionaire
    {
        public int QId { get; set; }
        public string Logo { get; set; }
        public Nullable<int> QOrder { get; set; }
        public string QTitle { get; set; }
        public string Question { get; set; }
        public string QAnswerS { get; set; }
        public string QAnswerL { get; set; }
        public string RevAnswerS { get; set; }
        public string RevAnswerL { get; set; }
        public Nullable<int> QAnswerVal { get; set; }
        public bool QShowYesNo { get; set; }
        public bool QShowMaybe { get; set; }
        public bool QShowShortA { get; set; }
        public bool QShowLongA { get; set; }
        public bool QIsMandVal { get; set; }
        public bool IsMandYesNo { get; set; }
        public bool IsMandShortA { get; set; }
        public bool IsMandLongA { get; set; }
        public bool RevShowYesNo { get; set; }
        public bool RevShowShortR { get; set; }
        public bool RevShowLongR { get; set; }
        public int RevAnswerVal { get; set; }
        public bool IsMandYesNoRev { get; set; }
        public bool IsMandShortRev { get; set; }
        public bool IsMandLongRev { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Dated { get; set; }
        public Nullable<System.DateTime> DateAnswered { get; set; }
        public Nullable<int> ProcessFlowId { get; set; }
        public Nullable<int> ProcessMasterId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> UserId { get; set; }
        public bool IsReviewed { get; set; }
        public Nullable<System.DateTime> DateReviewed { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public bool IsValid { get; set; }
        public bool IsInvalid { get; set; }
        public string ReviewerNote { get; set; }
        public bool IsDefault { get; set; }
        public string UserName { get; set; }
        public string UserPic { get; set; }
        public string ReviewerName { get; set; }
        public string ReviewerPic { get; set; }
        public string ProcessName { get; set; }
        public string BUnitAbbr { get; set; }
        public string BUnitName { get; set; }
        public string ProjectSerial { get; set; }
        public string ProcessSerial { get; set; }
        public bool ForceAnalize { get; set; }
        public bool AllowAnalize { get; set; }
        public int OptimalValue { get; set; }
        public string OptimalShort { get; set; }
        public string OptimalLong { get; set; }
        public int QMasterId { get; set; }
        public bool AllowFile { get; set; }
        public string FileUrl { get; set; }
        public Nullable<int> FileId { get; set; }
        public bool AllowLink { get; set; }
        public string LinkUrl { get; set; }
        public Nullable<int> LinkId { get; set; }
        public Nullable<int> QGroupId { get; set; }
    }
}
