//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_RequestDetails
    {
        public int Id { get; set; }
        public string ProductCode { get; set; }
        public string RequestNumber { get; set; }
        public string SubRequestNumber { get; set; }
        public string SubRequestType { get; set; }
        public string PartyName { get; set; }
        public string AccountNumber { get; set; }
        public string AccountCategory { get; set; }
        public string ESSubSegment { get; set; }
        public string RatePlan { get; set; }
        public string RatePlanDescription { get; set; }
        public string VariableAmount_MRC { get; set; }
        public string VariableAmount_OTC { get; set; }
        public string VariableAmount_QRC { get; set; }
        public string VariableAmount_YRC { get; set; }
        public string ContractPeriod { get; set; }
        public string ChargeDetails { get; set; }
        public string ApprovalRequestStatusName { get; set; }
        public string CBCMStatus { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> PartyId { get; set; }
    }
}
