//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_RawToRequestTrans
    {
        public int ProductCodeId { get; set; }
        public string RequestNumber { get; set; }
        public string SubRequestNumber { get; set; }
        public int RequestTypeId { get; set; }
        public Nullable<int> PartyId { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<int> AcctCategoryId { get; set; }
        public Nullable<int> ESSegmentId { get; set; }
        public int RatePlanId { get; set; }
        public Nullable<int> ContractId { get; set; }
        public Nullable<int> ApprovalRequestStatusId { get; set; }
        public Nullable<double> VariableAmount_MRC { get; set; }
        public Nullable<double> VariableAmount_OTC { get; set; }
        public string VariableAmount_QRC { get; set; }
        public string VariableAmount_YRC { get; set; }
        public string Created { get; set; }
        public string ChargeDetails { get; set; }
    }
}
