//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserGroups
    {
        public int UserId { get; set; }
        public string UserName { get; set; }
        public int GroupId { get; set; }
        public string GroupName { get; set; }
        public bool UserDeleted { get; set; }
        public bool GroupDeleted { get; set; }
        public bool CompanyDeleted { get; set; }
        public string CompanyName { get; set; }
        public string UserFName { get; set; }
        public Nullable<System.DateTime> UserDOB { get; set; }
        public string UserEmail { get; set; }
        public string UserPic { get; set; }
        public bool IsActive { get; set; }
        public string UserLastName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public Nullable<System.DateTime> LastPasswordFailureDate { get; set; }
        public int PasswordFailuresSinceLastSuccess { get; set; }
        public Nullable<System.DateTime> PasswordChangedDate { get; set; }
        public int GroupMembershipId { get; set; }
        public string GroupLogo { get; set; }
        public Nullable<System.DateTime> GroupMembershipDate { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public int CompanyId { get; set; }
        public int DivisionId { get; set; }
        public int BUnitId { get; set; }
        public Nullable<int> ParentGroupId { get; set; }
        public Nullable<int> CollectiveGroupId { get; set; }
        public bool isGroupActive { get; set; }
        public string UserGUID { get; set; }
    }
}
