//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_userslist
    {
        public int UserId { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> IsConfirmed { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public Nullable<System.DateTime> LastPasswordFailureDate { get; set; }
        public string Provider { get; set; }
        public string UserFName { get; set; }
        public string UserPic { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string UserLastName { get; set; }
    }
}
