//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_UserProfile_BUnits
    {
        public int UserId { get; set; }
        public string UserGUID { get; set; }
        public string UserName { get; set; }
        public string UserFName { get; set; }
        public string UserSName { get; set; }
        public string UserLastName { get; set; }
        public string UserFullNAme { get; set; }
        public string UserInitial { get; set; }
        public Nullable<System.DateTime> UserDOB { get; set; }
        public string UserEmail { get; set; }
        public string UserTelephone { get; set; }
        public string UserMobile { get; set; }
        public string UserPic { get; set; }
        public string UserAddress { get; set; }
        public string UserCity { get; set; }
        public string UserCountryId { get; set; }
        public string UserAbout { get; set; }
        public int UserCompanyId { get; set; }
        public int UserBUnitId { get; set; }
        public Nullable<int> UserEmployeeNumber { get; set; }
        public string UserEmployeeSerial { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> ActivationDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletionDate { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
        public string GroupList { get; set; }
        public string GroupListIds { get; set; }
        public Nullable<int> LoggedInBUnitId { get; set; }
        public string LoggedInBUnitGUID { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public string BUnitAbbr { get; set; }
        public string BUnitName { get; set; }
        public string BUnitSerial { get; set; }
        public string DivAbbr { get; set; }
        public string DivName { get; set; }
        public string DivSerial { get; set; }
        public Nullable<int> LoggedInDivisionId { get; set; }
        public string LoggedInDivisionGUID { get; set; }
        public Nullable<int> LoggedInCompanyId { get; set; }
        public string LoggedInCompanyGUID { get; set; }
        public string ComAbbr { get; set; }
        public string ComName { get; set; }
        public string ComSerial { get; set; }
        public Nullable<bool> LoggedInBUnitPrivilaged { get; set; }
        public Nullable<bool> LoggedInDivisionPrivilaged { get; set; }
        public Nullable<bool> LoggedInCompanyPrivilaged { get; set; }
        public Nullable<int> ComBaseUserGroupId { get; set; }
        public Nullable<int> UnitBaseUserGroupId { get; set; }
        public Nullable<int> DivBaseUserGroupId { get; set; }
    }
}
