//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_VoteTDetails
    {
        public int Id { get; set; }
        public int VoteTMainId { get; set; }
        public int UserId { get; set; }
        public string UserName { get; set; }
        public string UserPic { get; set; }
        public Nullable<int> UserConformance { get; set; }
        public string UserInitial { get; set; }
        public string UserComment { get; set; }
        public Nullable<System.DateTime> DateActioned { get; set; }
        public System.DateTime DateCreated { get; set; }
        public bool IsActive { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<int> ProcessId { get; set; }
        public Nullable<int> OriginatorId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public bool IsDeletedD { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<int> DelegateId { get; set; }
        public string DelegateGUID { get; set; }
        public string DelegateName { get; set; }
        public string DelegatePic { get; set; }
        public string DelegateEmail { get; set; }
    }
}
