//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_VoteMaster
    {
        public int Id { get; set; }
        public string Number { get; set; }
        public string Serial { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int UserId { get; set; }
        public int OwnerId { get; set; }
        public Nullable<int> PartnerId { get; set; }
        public Nullable<int> ReviewerId { get; set; }
        public Nullable<int> RefProcessId { get; set; }
        public string RefProcessNo { get; set; }
        public int LocationId { get; set; }
        public Nullable<int> SubLocationId { get; set; }
        public string LocationTxt { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateExtension { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public int FlowTypeId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public double StatusPercent { get; set; }
        public int StatusVal { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<int> BUnitId { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public Nullable<bool> Mark { get; set; }
        public Nullable<int> MarkSeq { get; set; }
        public string MarkLogo { get; set; }
        public string RootId { get; set; }
        public bool IsTemp { get; set; }
        public bool IsKey { get; set; }
        public bool RenderInLine { get; set; }
        public bool RenderAutoOpen { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public int IsPosted { get; set; }
        public Nullable<int> Extra1 { get; set; }
        public string Extra2 { get; set; }
        public string Taggs { get; set; }
        public string UserTaggs { get; set; }
        public string BUnitAbbr { get; set; }
        public string BUnitName { get; set; }
        public string ProjectSerial { get; set; }
        public string ProjectTitle { get; set; }
        public System.DateTime ProjectStartDate { get; set; }
        public System.DateTime ProjectEndtDate { get; set; }
        public string ProjectCountry { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserTelephone { get; set; }
        public string UserMobile { get; set; }
        public string UserPic { get; set; }
        public string OwnerName { get; set; }
        public string OwnerEmail { get; set; }
        public string OwnerTele { get; set; }
        public string OwnerMobile { get; set; }
        public string OwnerPic { get; set; }
        public string ReviewerName { get; set; }
        public string ReviewerEmail { get; set; }
        public string ReviewerTele { get; set; }
        public string ReviewerMobile { get; set; }
        public string ReviewerPic { get; set; }
        public string ProjectPic { get; set; }
        public string FlowName { get; set; }
        public string FlowAbbr { get; set; }
        public string FlowDesc { get; set; }
        public string FlowTitle { get; set; }
        public string Logo { get; set; }
        public string RClassA { get; set; }
        public string RClassB { get; set; }
        public string RClassC { get; set; }
        public Nullable<int> TotalSuccess { get; set; }
        public Nullable<int> TotalFailure { get; set; }
        public Nullable<int> TotalNeurtal { get; set; }
        public Nullable<int> TotalVoteLike { get; set; }
        public Nullable<int> TotalVoteDislike { get; set; }
        public Nullable<int> TotalActiveActionUnits { get; set; }
        public Nullable<int> TotalActiveActionUnitsCompleted { get; set; }
        public Nullable<int> TotalActiveSections { get; set; }
        public Nullable<int> TotalActiveSectionsCompleted { get; set; }
        public Nullable<int> TotalActiveStages { get; set; }
        public Nullable<int> TotalActiveStagesCompleted { get; set; }
        public int ProcessStructCoreId { get; set; }
    }
}
