//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_WorkSpaceT
    {
        public int WorkSpaceId { get; set; }
        public string Number { get; set; }
        public string Serial { get; set; }
        public int Type { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int ParentId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public Nullable<System.DateTime> DateClosed { get; set; }
        public Nullable<int> OwnerId { get; set; }
        public string Logo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string State { get; set; }
        public string CountryId { get; set; }
        public string AdminUserList { get; set; }
        public string AdminUserListIds { get; set; }
        public string MemberUserList { get; set; }
        public string MemberUserListIds { get; set; }
        public int Account { get; set; }
        public int StatusVal { get; set; }
        public double StatusPercent { get; set; }
        public int BUnitId { get; set; }
        public int DivisionId { get; set; }
        public int CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime Dated { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserTelephone { get; set; }
        public string UserMobile { get; set; }
        public string UserPic { get; set; }
        public string BUnitAbbr { get; set; }
        public string BUnitName { get; set; }
        public string BUnitGUID { get; set; }
        public string AuditorUserList { get; set; }
        public string AuditorUserListIds { get; set; }
        public Nullable<int> AdminUsersGroupId { get; set; }
        public Nullable<int> MemberUsersGroupId { get; set; }
        public Nullable<int> AuditorUsersGroupId { get; set; }
        public Nullable<int> FolderId { get; set; }
        public string Abbr { get; set; }
        public string DivAbbr { get; set; }
        public string DivName { get; set; }
        public string DivGUID { get; set; }
        public string ComAbbr { get; set; }
        public string ComName { get; set; }
        public string ComGUID { get; set; }
        public Nullable<int> BaseUserGroupId { get; set; }
        public string WorkGUID { get; set; }
        public bool AllowIntro { get; set; }
        public bool AllowProjects { get; set; }
        public bool AllowProcess { get; set; }
        public bool AllowFiles { get; set; }
        public bool AllowUsers { get; set; }
        public bool AllowLog { get; set; }
        public bool AllowCharts { get; set; }
        public bool AllowIntroOpen { get; set; }
        public bool AllowProjectsOpen { get; set; }
        public bool AllowProcessOpen { get; set; }
        public bool AllowFilesOpen { get; set; }
        public bool AllowUsersOpen { get; set; }
        public bool AllowLogOpen { get; set; }
        public bool AllowChartsOpen { get; set; }
        public bool AllowExtra { get; set; }
        public bool AllowExtraOpen { get; set; }
        public bool AllowGalary { get; set; }
        public bool AllowGalaryOpen { get; set; }
        public string UserGUID { get; set; }
        public string UserCountryId { get; set; }
        public string UserInitial { get; set; }
        public Nullable<int> SystemFolderId { get; set; }
        public Nullable<int> ProjectFolderId { get; set; }
        public Nullable<int> ProcessFolderId { get; set; }
        public Nullable<int> FeedsFolderId { get; set; }
        public Nullable<int> LibraryFolderId { get; set; }
        public Nullable<int> GeneralFolderId { get; set; }
        public bool AllowFeeds { get; set; }
        public bool AllowFeedsOpen { get; set; }
        public bool AllowStatistics { get; set; }
        public bool AllowStatisticOpen { get; set; }
        public bool AllowEx1 { get; set; }
        public bool AllowEx1Open { get; set; }
        public bool AllowEx2 { get; set; }
        public bool AllowEx2Open { get; set; }
        public bool AllowSummary { get; set; }
        public bool AllowSummaryOpen { get; set; }
        public Nullable<int> ExtraField1 { get; set; }
        public Nullable<int> ExtraField2 { get; set; }
        public string WordspaceHeader { get; set; }
        public Nullable<int> ParentBUnitUserGroupId { get; set; }
        public string BUnitCountryId { get; set; }
    }
}
