//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_WorldMap2
    {
        public Nullable<int> Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string Color { get; set; }
        public string CodeLL { get; set; }
        public string Latitude { get; set; }
        public string Longitude { get; set; }
        public string Code2 { get; set; }
        public string BUnitName { get; set; }
        public int BUnitType { get; set; }
        public string BUnitAbbr { get; set; }
        public string BUnitGUID { get; set; }
        public string BUnitSerial { get; set; }
        public int BUnitParentId { get; set; }
        public Nullable<int> TransactionLogCount { get; set; }
        public Nullable<int> ProcessCount { get; set; }
    }
}
